export default {
  next: require('../assets/images/next.png'),
  home: require('../assets/images/home.png'),
  task: require('../assets/images/checklist.png'),
  setting: require('../assets/images/settings.png'),
  profile: require('../assets/images/profile.png'),
  logout: require('../assets/images/logout.png'),
  task: require('../assets/images/task.png'),
  project: require('../assets/images/project.png'),
  back: require('../assets/images/left.png'),
  more: require('../assets/images/more.png'),
  error: require('../assets/images/Error.png'),
  info: require('../assets/images/Info.png'),
  success: require('../assets/images/Success.png'),
  warning: require('../assets/images/Warning.png'),
};
